services:
  couchdb:
    image: couchdb:3.3
    container_name: biar-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - biar-network

  tika:
    image: logicalspark/docker-tikaserver:latest
    container_name: biar-tika
    restart: unless-stopped
    ports:
      - "9998:9998"
    networks:
      - biar-network

  solr:
    image: solr:9
    container_name: biar-solr
    restart: unless-stopped
    ports:
      - "8983:8983"
    environment:
      SOLR_HEAP: 512m
    volumes:
      - solr_data:/var/solr
    networks:
      - biar-network
    command:
      - sh
      - -c
      - "solr-precreate biar_docs /opt/solr/server/solr/configsets/sample_techproducts_configs"

  nifi:
    image: apache/nifi:1.24.0
    container_name: biar-nifi
    restart: unless-stopped
    ports:
      - "8080:8080"     # NiFi UI
      - "8081:8081"   # ListenHTTP (Tika â†’ NiFi)
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin123456789
      NIFI_JVM_HEAP_INIT: 512m
      NIFI_JVM_HEAP_MAX: 1g
    volumes:
      - nifi_data:/opt/nifi/nifi-current/logs
    networks:
      - biar-network

  minio:
    image: minio/minio:latest
    container_name: biar-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks:
      - biar-network    


  ozone:
    image: apache/ozone:1.4.0
    container_name: biar-ozone
    hostname: ozone
    restart: unless-stopped
    ports:
      - "9862:9862"   # SCM
      - "9876:9876"   # OM
      - "9878:9878"   # S3 Gateway
    volumes:
      - ozone_data:/data/ozone
    environment:
      OZONE_SCM_NAMES: ozone
      OZONE_OM_ADDRESS: ozone
      OZONE_S3G_ADDRESS: ozone
    command: >
      bash -c "
      ozone scm --init &&
      ozone scm &
      sleep 5 &&
      ozone om &
      sleep 5 &&
      ozone datanode &
      sleep 5 &&
      ozone s3g &&
      tail -f /dev/null
      "
    networks:
      - biar-network

volumes:
  couchdb_data:
  solr_data:
  nifi_data:
  ozone_data:
  minio_data:

networks:
  biar-network: